### ISSUE TITLE
🐛  Bug: Keyboard highlighting broken for repeated letters

### ISSUE THREAD

**Issue by alexownejazayeri** [alexownejazayeri/code-le#10]
# Steps to reproduce
- CODE-LE: 'regex'
- Turn 0: 'webgl'
- Turn 1: 'audio'
- Turn 2: 'const'
- Turn 3: 'regex'

# Expected behavior
'E' key highlights yellow on first guess and green on success

# Actual behavior
'E' key isn't highlighting at all.

I think this came about from a Netlify CI/CD test that failed because it didn't like that a ternary was returning a null value, so I commented it out and it seemed to work. Would start there!

# To-Do

- [x] Review the [Keyboard](https://github.com/alexownejazayeri/code-le/blob/master/src/components/Game/Keyboard.js) component for a buggy bit of commented out code
- [x] Uncomment and see if the behavior stops
- [x] Refactor to use an if-check since returning `null` is a bad practice

**Comment by alexownejazayeri** [comment]
# Solve

## Bug location

The file Keyboard.js (locations: `src/components/Keyboard.js`) had this commented bit of code in the `keyGenerator` function.

## Overview

- During a previous deploy through Netlify, their CI/CD included a test suite that wouldn't deploy due to anti pattern of using a ternary that returns null (instead of an if-check, for example)

## The code / solve

```javascript
// If it occurs more than once, check the same for every occurence    <-- this explains why it happened on repeat chars
              if (charNum > 1) {
                answerIndicesArr = round[0]
                  .map((letter, i) => (letter === lowerChar ? i : null))
                  .filter((el) => typeof el === "number");
                if (!repeatCharAttemptedIndices.includes(j)) {
                  repeatCharAttemptedIndices.push(j);
                }
                /* !repeatCharAttemptedIndices.includes(j)        // This was the buggy code that got commented out
                  ? repeatCharAttemptedIndices.push(j)
                  : null; */
              }
```

## Summary

- Replaced the commented out code (naively, did this to pass the test and deploy)
- Opening a PR to merge this code into the master branch and push to production

**Comment by alexownejazayeri** [comment]
# Update

Realizing the whole `keyGenerator` function can be moved into a module to make `Keyboard.js` more readable.

## To-do
- [ ] Move `Keyboard.js` into `/modules/keyboard-mgmt.js`
- [ ] Write unit tests for this and the rest of the module functions
