### ISSUE TITLE
🧪 Write first round of simple unit, integration, and end-to-end (e2e) tests

### ISSUE THREAD

**Issue by alexownejazayeri** [alexownejazayeri/code-le#11]
# Writing tests

## Overview
Part of a larger effort to learn CI/CD and concepts from test-driven development (TDD).

### Learn
Learn best practices and create write-ups to review and share with others who are getting started with testing.

- [x] Research Jest for unit testing React apps + add to #100DaysOfCode
- [x] Research Jest & React Testing Library for integration testing + add to #100DaysOfCode
- [x] Research Cypress for end-to-end (e2e) testing + add to #100DaysOfCode

### Do
Implement these best practices for code-le. Start with the basics and come back if makes sense.

- [x] Unit tests against high-value components
- [x] Basic integration tests (a handful)
- [x] An E2E test
- [x] Try for 60- 70% coverage as an exercise knowing this can be a misleading goal

### Teach
Solidify learning by creating resources for others to learn.

- [ ] #42
- [ ] #43
- [ ] #44
- [ ] #45

**Comment by alexownejazayeri** [comment]
#  Research Jest for unit testing React apps + add to #100DaysOfCode

Working on this subtask today. Got some good advice re: testing from a mentor...

> I'd say it's not bad to know - but it's not a high priority really for getting your first role

## Research & Learning

- [ ] Max Schwarz Udemy module
- [ ] Traversy tutorial
- [ ] Post notes via Goodnotes into #100DaysOfCode project for future content production

**Comment by alexownejazayeri** [comment]
# Close to 100% code coverage w/ Unit tests

## Unit test ideas

- [ ] Mock functions that manage data in localStorage to avoid making unnecessary changes
- [ ] Put a unit test against each component
  - [ ] Does it render what it's supposed to?
  - [ ] Does it handle user interactions correctly?
  - [ ] Success and failure cases for state changes?

**Comment by alexownejazayeri** [comment]
# Do
Implement unit, integration, and e2e testing.

## Unit testing (some ideas for now)

- [ ] Mock functions that manage data in localStorage to avoid making unnecessary changes
- [ ] Put a unit test against each component
  - [ ] Does it render what it's supposed to?
  - [ ] Does it handle user interactions correctly?
  - [ ] Success and failure cases for state changes?

**Comment by alexownejazayeri** [comment]
# Teach

## Consolidate learnings
- [ ] Summarize learnings in #100DaysOfCode via .md notes
