### ISSUE TITLE
Simplify game state w/ array ops

### ISSUE THREAD

**Issue by alexownejazayeri** [alexownejazayeri/code-le#14]
# Simplify state
This one's short and sweet. The game state contains a matrix that's rich with implicit data. See if there's a way to clean up the statefulness of the app by trading state for a function somewhere else.

Evaluate performance differences too. Might end up being slower to pull state out of the games state.

## To-do
- [ ] Evaluate the app for redundant state e.g.(tile row evaluations, keyboard state, etc.)
- [ ] Simplify state in a separate branch
- [ ] Run performance tests to evaluate which version outperforms

**Comment by alexownejazayeri** [comment]
# Note

Consider simplifying state with `useContext` for components that need it. Also map out the components as they are now and maintain a diagram of how state flows between them so it's not such a task to understand what's happening.
