### ISSUE TITLE
Add CHANGELOG.md

### ISSUE THREAD

**Issue by alexownejazayeri** [alexownejazayeri/code-le#29]
# Manage VCS, SemVer, and Release Workflow
Set up a changelog to track how this project develops over time and get a sense for how Agile works in a controlled environment.

## To-Do

- [ ] Add CHANGELOG
- [ ] Research a workflow to automate release info
- [ ] Learn and implement alpha/beta and semver best practices
- [ ] Research Agile 101 and take notes

**Comment by alexownejazayeri** [comment]
# Resources
- [GitHub - About Releases](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases)
