### ISSUE TITLE
Consolidate CI/CD and testing knowledge

### ISSUE THREAD

**Issue by alexownejazayeri** [alexownejazayeri/code-le#42]

**Comment by alexownejazayeri** [comment]
# Todo

## Consolidate GoodNotes -> Figma
- [ ] Transfer all CI/CD & Testing notes to Figma

## Create content
- [ ] One-pagers
- [ ] LinkedIn mega post
- [ ] Twitter thread
- [ ] Create a small video series with examples (YouTube playlist)
